import hashlib
from datetime import date

from jinja2 import BaseLoader, Environment

from app.modules.annex_iv_core.schemas import ANNEX_IV_SECTIONS, SECTION_NAMES

PDF_HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<style>
  @page {
    size: A4;
    margin: 2cm 2.5cm;
    @bottom-center {
      content: "Generated by CompliAI | {{ gen_date }} | Revision hash: {{ revision_hash }}";
      font-size: 8pt;
      color: #888;
    }
    @top-right {
      content: "Page " counter(page) " of " counter(pages);
      font-size: 8pt;
      color: #888;
    }
  }
  body {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 10pt;
    color: #222;
    line-height: 1.5;
  }
  .cover {
    text-align: center;
    padding-top: 4cm;
    page-break-after: always;
  }
  .cover .logo {
    font-size: 28pt;
    font-weight: bold;
    color: #1a56db;
  }
  .cover .subtitle {
    font-size: 14pt;
    color: #555;
    margin-top: 0.5cm;
  }
  .cover .meta {
    margin-top: 2cm;
    font-size: 11pt;
    color: #333;
  }
  .cover .meta table {
    margin: 0 auto;
    border-collapse: collapse;
  }
  .cover .meta td {
    padding: 4px 12px;
    text-align: left;
  }
  .cover .meta .label {
    font-weight: bold;
    color: #555;
  }
  .cover .badge {
    display: inline-block;
    margin-top: 1cm;
    padding: 6px 16px;
    border-radius: 4px;
    font-size: 10pt;
    font-weight: bold;
  }
  .badge-draft { background: #fef3c7; color: #92400e; border: 1px solid #f59e0b; }
  .badge-approved { background: #d1fae5; color: #065f46; border: 1px solid #10b981; }
  .badge-archived { background: #f3f4f6; color: #6b7280; border: 1px solid #d1d5db; }
  h1 { font-size: 18pt; color: #1a56db; border-bottom: 2px solid #1a56db; padding-bottom: 4px; margin-top: 0.8cm; }
  h2 { font-size: 13pt; color: #1e40af; margin-top: 0.6cm; }
  h3 { font-size: 11pt; color: #374151; margin-top: 0.4cm; }
  .section-block { page-break-inside: avoid; margin-bottom: 1cm; }
  .section-header {
    background: #eff6ff;
    border-left: 4px solid #1a56db;
    padding: 6px 12px;
    margin-bottom: 8px;
  }
  .section-header h1 { font-size: 13pt; margin: 0; border: none; color: #1e40af; }
  .field-row { margin-bottom: 8px; padding: 6px 0; border-bottom: 1px solid #f0f0f0; }
  .field-label { font-weight: bold; font-size: 9pt; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; }
  .field-value { margin-top: 2px; font-size: 10pt; color: #111; white-space: pre-wrap; word-break: break-word; }
  .field-empty { color: #d1d5db; font-style: italic; }
  .completeness-bar-bg {
    background: #e5e7eb; height: 8px; border-radius: 4px; width: 100%; margin-top: 4px;
  }
  .completeness-bar-fill {
    height: 8px; border-radius: 4px; background: #10b981;
  }
  .evidence-block { margin-top: 8px; padding: 6px 10px; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 4px; }
  .evidence-block .ev-title { font-weight: bold; font-size: 9pt; color: #374151; }
  .toc { margin-bottom: 1cm; }
  .toc table { border-collapse: collapse; width: 100%; }
  .toc td { padding: 4px 8px; border-bottom: 1px solid #f0f0f0; }
  .toc .toc-num { color: #1a56db; font-weight: bold; width: 2cm; }
  .toc .toc-score { text-align: right; color: #6b7280; }
</style>
</head>
<body>

<div class="cover">
  <div class="logo">CompliAI</div>
  <div class="subtitle">EU AI Act — Annex IV Technical File</div>
  <div class="meta">
    <table>
      <tr><td class="label">Organisation</td><td>{{ org_name }}</td></tr>
      <tr><td class="label">AI System</td><td>{{ system_name }}</td></tr>
      <tr><td class="label">Revision</td><td>{{ revision_version }}</td></tr>
      <tr><td class="label">Generated</td><td>{{ gen_date }}</td></tr>
    </table>
    <div class="badge badge-{{ revision_status }}">{{ revision_status | upper }}</div>
  </div>
</div>

<h1>Table of Contents</h1>
<div class="toc">
  <table>
    {% for num, name in section_names.items() %}
    <tr>
      <td class="toc-num">§{{ num }}</td>
      <td>{{ name }}</td>
      <td class="toc-score">
        {% set score = section_scores.get(num, 0) %}
        {{ (score * 100) | int }}% complete
      </td>
    </tr>
    {% endfor %}
  </table>
</div>

{% for num in range(1, 10) %}
{% set section = sections_data.get(num, {}) %}
{% set schema = section_schema.get(num, {}) %}
<div class="section-block">
  <div class="section-header">
    <h1>Section {{ num }}: {{ section_names[num] }}</h1>
  </div>
  {% set score = section_scores.get(num, 0) %}
  <div style="font-size:9pt; color:#6b7280; margin-bottom:6px;">
    Completeness: {{ (score * 100) | int }}%
    <div class="completeness-bar-bg">
      <div class="completeness-bar-fill" style="width:{{ (score * 100) | int }}%;"></div>
    </div>
  </div>

  {% for field_key, field_meta in schema.items() %}
  <div class="field-row">
    <div class="field-label">
      {{ field_meta.label }}{% if field_meta.required %} <span style="color:#ef4444">*</span>{% endif %}
    </div>
    {% set val = section.get(field_key) %}
    {% if val %}
    <div class="field-value">{% if val is iterable and val is not string %}{{ val | join(", ") }}{% else %}{{ val }}{% endif %}</div>
    {% else %}
    <div class="field-value field-empty">Not provided</div>
    {% endif %}
  </div>
  {% endfor %}

  {% if evidence_by_section.get(num) %}
  <h3>Supporting Evidence</h3>
  {% for ev in evidence_by_section[num] %}
  <div class="evidence-block">
    <div class="ev-title">{{ ev.type | upper }}: {{ ev.filename or ev.url or ev.source or "Unnamed" }}</div>
    {% if ev.source %}<div>Source: {{ ev.source }}</div>{% endif %}
    {% if ev.version %}<div>Version: {{ ev.version }}</div>{% endif %}
    {% if ev.field_key %}<div>Field: {{ ev.field_key }}</div>{% endif %}
  </div>
  {% endfor %}
  {% endif %}
</div>
{% endfor %}

</body>
</html>
"""


def _build_template_context(revision, ai_system, org) -> dict:
    from app.modules.annex_iv_core.completeness import calculate_section_completeness

    sections_data: dict[int, dict] = {}
    section_scores: dict[int, float] = {}
    evidence_by_section: dict[int, list] = {}

    for section in revision.sections:
        sections_data[section.section_number] = section.content or {}
        score, _ = calculate_section_completeness(section.section_number, section.content or {})
        section_scores[section.section_number] = score
        section_evidences = [
            ev for ev in (revision.evidence_attachments or []) if ev.section_id == section.id
        ]
        evidence_by_section[section.section_number] = section_evidences

    revision_hash = hashlib.sha256(str(revision.id).encode()).hexdigest()[:16]

    return {
        "org_name": org.name,
        "system_name": ai_system.name,
        "revision_version": revision.version,
        "revision_status": revision.status,
        "gen_date": date.today().isoformat(),
        "revision_hash": revision_hash,
        "sections_data": sections_data,
        "section_schema": ANNEX_IV_SECTIONS,
        "section_names": SECTION_NAMES,
        "section_scores": section_scores,
        "evidence_by_section": evidence_by_section,
    }


def generate_technical_file_pdf(revision, ai_system, org) -> bytes:
    """Generate PDF bytes for the given Technical File revision."""
    from weasyprint import HTML

    env = Environment(loader=BaseLoader())
    template = env.from_string(PDF_HTML_TEMPLATE)
    ctx = _build_template_context(revision, ai_system, org)
    html_content = template.render(**ctx)
    return HTML(string=html_content).write_pdf()


def generate_markdown_export(revision, ai_system, org) -> str:
    """Generate Markdown export for the given Technical File revision."""
    from app.modules.annex_iv_core.completeness import calculate_section_completeness

    revision_hash = hashlib.sha256(str(revision.id).encode()).hexdigest()[:16]
    gen_date = date.today().isoformat()

    lines: list[str] = []
    lines.append("# EU AI Act — Annex IV Technical File")
    lines.append("")
    lines.append(f"**Organisation:** {org.name}  ")
    lines.append(f"**AI System:** {ai_system.name}  ")
    lines.append(f"**Revision:** {revision.version} ({revision.status.upper()})  ")
    lines.append(f"**Generated:** {gen_date}  ")
    lines.append(f"**Revision Hash:** {revision_hash}  ")
    lines.append("")
    lines.append("---")
    lines.append("")

    sections_by_num = {s.section_number: s for s in revision.sections}

    for num in range(1, 10):
        section_name = SECTION_NAMES[num]
        lines.append(f"## Section {num}: {section_name}")
        lines.append("")

        section = sections_by_num.get(num)
        content = section.content if section else {}
        score, missing = calculate_section_completeness(num, content or {})
        lines.append(f"> **Completeness:** {int(score * 100)}%")
        lines.append("")

        schema = ANNEX_IV_SECTIONS.get(num, {})
        for field_key, field_meta in schema.items():
            label = field_meta["label"]
            required_marker = " *(required)*" if field_meta["required"] else ""
            lines.append(f"### {label}{required_marker}")
            val = content.get(field_key) if content else None
            if val:
                if isinstance(val, list):
                    for item in val:
                        lines.append(f"- {item}")
                else:
                    lines.append(str(val))
            else:
                lines.append("*Not provided*")
            lines.append("")

        # Evidence for this section
        if section:
            section_evidence = [
                ev for ev in (revision.evidence_attachments or []) if ev.section_id == section.id
            ]
            if section_evidence:
                lines.append("**Supporting Evidence:**")
                for ev in section_evidence:
                    label_ev = ev.filename or ev.url or ev.source or "Unnamed"
                    lines.append(f"- [{ev.type.upper()}] {label_ev}")
                lines.append("")

        lines.append("---")
        lines.append("")

    lines.append(f"*Generated by CompliAI | {gen_date} | Revision hash: {revision_hash}*")
    return "\n".join(lines)
