"""Portfolio aggregate report generator (Epic 7 — E7-US3 / T5.6).

Exports compliance status for all AI systems in an organisation:
  - PDF  — executive summary table + per-system details
  - CSV  — flat spreadsheet for regulators / board
"""

from __future__ import annotations

import csv
import io
from datetime import date
from typing import TYPE_CHECKING

from jinja2 import BaseLoader, Environment

if TYPE_CHECKING:
    from app.models.organization import Organization


# ── Data helpers ──────────────────────────────────────────────────────────────


def _system_row(system, latest_revision, open_violations: int) -> dict:
    """Build a single row dict for a system."""
    from app.modules.annex_iv_core.completeness import calculate_revision_completeness

    completeness = 0.0
    days_since_revision = None

    if latest_revision:
        scores, _ = calculate_revision_completeness(latest_revision)
        completeness = (sum(scores.values()) / len(scores)) if scores else 0.0
        if latest_revision.created_at:
            from datetime import UTC, datetime

            now = datetime.now(UTC).replace(tzinfo=None)
            days_since_revision = (now - latest_revision.created_at).days

    return {
        "id": str(system.id),
        "name": system.name,
        "category": system.category,
        "status": system.status,
        "completeness_pct": round(completeness * 100, 1),
        "open_violations": open_violations,
        "days_since_revision": days_since_revision,
        "revision_version": latest_revision.version if latest_revision else None,
    }


def build_portfolio_data(org, systems, db) -> list[dict]:
    """Return a list of row dicts for every system in the org."""
    from app.models.policy import ComplianceEvent
    from app.models.technical_file import TechnicalFile, TechnicalFileRevision

    rows = []
    for system in systems:
        # Fetch latest revision
        tf = db.query(TechnicalFile).filter(TechnicalFile.ai_system_id == system.id).first()
        latest_revision = None
        if tf and tf.current_revision_id:
            latest_revision = (
                db.query(TechnicalFileRevision)
                .filter(TechnicalFileRevision.id == tf.current_revision_id)
                .first()
            )

        # Count open violations
        open_violations = (
            db.query(ComplianceEvent)
            .filter(
                ComplianceEvent.ai_system_id == system.id,
                ComplianceEvent.status == "open",
            )
            .count()
        )

        rows.append(_system_row(system, latest_revision, open_violations))

    return rows


# ── CSV export ────────────────────────────────────────────────────────────────

_CSV_FIELDS = [
    "name",
    "category",
    "status",
    "completeness_pct",
    "open_violations",
    "days_since_revision",
    "revision_version",
]

_CSV_HEADERS = [
    "System Name",
    "Category",
    "Status",
    "Completeness (%)",
    "Open Violations",
    "Days Since Last Revision",
    "Current Revision",
]


def generate_portfolio_csv(org, rows: list[dict]) -> bytes:
    """Generate a UTF-8 CSV byte string for the portfolio."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["CompliAI — Compliance Portfolio Report"])
    writer.writerow([f"Organisation: {org.name}", f"Generated: {date.today().isoformat()}"])
    writer.writerow([])
    writer.writerow(_CSV_HEADERS)
    for row in rows:
        writer.writerow([row.get(f, "") for f in _CSV_FIELDS])
    return buf.getvalue().encode("utf-8-sig")  # BOM for Excel compatibility


# ── PDF export ────────────────────────────────────────────────────────────────

_PORTFOLIO_PDF_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<style>
  @page {
    size: A4 landscape;
    margin: 1.5cm 2cm;
    @bottom-center {
      content: "Generated by CompliAI | {{ gen_date }} | Page " counter(page) " of " counter(pages);
      font-size: 8pt; color: #888;
    }
  }
  body { font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; font-size: 10pt; color: #222; }
  .cover { text-align: center; padding: 2cm 0 1cm; }
  .cover .logo { font-size: 24pt; font-weight: bold; color: #1a56db; }
  .cover .subtitle { font-size: 13pt; color: #555; margin-top: 0.3cm; }
  .cover .meta { margin-top: 1cm; font-size: 11pt; }
  h1 { font-size: 16pt; color: #1a56db; border-bottom: 2px solid #1a56db; padding-bottom: 4px; }
  h2 { font-size: 12pt; color: #1e40af; margin-top: 0.5cm; }
  table { width: 100%; border-collapse: collapse; margin-top: 0.5cm; font-size: 9pt; }
  th { background: #1a56db; color: white; padding: 6px 10px; text-align: left; }
  td { padding: 6px 10px; border-bottom: 1px solid #e5e7eb; }
  tr:nth-child(even) td { background: #f9fafb; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 8pt; font-weight: bold; }
  .green { background: #d1fae5; color: #065f46; }
  .yellow { background: #fef3c7; color: #92400e; }
  .red { background: #fee2e2; color: #991b1b; }
  .summary-grid { display: flex; gap: 1.5cm; margin: 0.8cm 0; }
  .kpi-card { flex: 1; border: 1px solid #e5e7eb; border-radius: 8px; padding: 0.4cm 0.6cm; text-align: center; }
  .kpi-value { font-size: 22pt; font-weight: bold; color: #1a56db; }
  .kpi-label { font-size: 8pt; color: #6b7280; margin-top: 2px; }
  .bar-bg { background: #e5e7eb; height: 6px; border-radius: 3px; min-width: 60px; display: inline-block; vertical-align: middle; }
  .bar-fill { height: 6px; border-radius: 3px; display: inline-block; }
</style>
</head>
<body>

<div class="cover">
  <div class="logo">CompliAI</div>
  <div class="subtitle">Compliance Portfolio Report</div>
  <div class="meta">
    <strong>{{ org_name }}</strong><br/>
    Generated: {{ gen_date }}
  </div>
</div>

<h1>Executive Summary</h1>

<div class="summary-grid">
  <div class="kpi-card">
    <div class="kpi-value">{{ total_systems }}</div>
    <div class="kpi-label">AI Systems</div>
  </div>
  <div class="kpi-card">
    <div class="kpi-value">{{ avg_completeness }}%</div>
    <div class="kpi-label">Avg Completeness</div>
  </div>
  <div class="kpi-card">
    <div class="kpi-value">{{ total_violations }}</div>
    <div class="kpi-label">Open Violations</div>
  </div>
  <div class="kpi-card">
    <div class="kpi-value">{{ at_risk_count }}</div>
    <div class="kpi-label">Systems at Risk</div>
  </div>
</div>

<h2>System Compliance Status</h2>

<table>
  <thead>
    <tr>
      <th>System Name</th>
      <th>Category</th>
      <th>Completeness</th>
      <th>Open Violations</th>
      <th>Days Since Revision</th>
      <th>Revision</th>
      <th>Risk</th>
    </tr>
  </thead>
  <tbody>
    {% for row in rows %}
    {% set risk = "green" if (row.completeness_pct >= 80 and row.open_violations == 0) else ("yellow" if row.completeness_pct >= 50 else "red") %}
    <tr>
      <td><strong>{{ row.name }}</strong></td>
      <td>{{ row.category | replace("_", " ") | title }}</td>
      <td>
        <div class="bar-bg" style="width:80px;">
          <div class="bar-fill" style="width:{{ row.completeness_pct }}%; background: {{ '#10b981' if row.completeness_pct >= 80 else ('#f59e0b' if row.completeness_pct >= 50 else '#ef4444') }};"></div>
        </div>
        {{ row.completeness_pct }}%
      </td>
      <td>{{ row.open_violations }}</td>
      <td>{{ row.days_since_revision if row.days_since_revision is not none else "—" }}</td>
      <td>{{ row.revision_version or "—" }}</td>
      <td><span class="badge {{ risk }}">{{ "Healthy" if risk == "green" else ("Attention" if risk == "yellow" else "At Risk") }}</span></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<p style="font-size:8pt; color:#888; margin-top:1cm;">
  This report was generated automatically by CompliAI.
  It reflects the state of the documentation at the time of export and should not be used as a
  substitute for a formal legal compliance review.
</p>

</body>
</html>
"""


def generate_portfolio_pdf(org, rows: list[dict]) -> bytes:
    """Generate a landscape A4 PDF for the portfolio compliance report."""
    from weasyprint import HTML

    total_systems = len(rows)
    avg_completeness = (
        round(sum(r["completeness_pct"] for r in rows) / total_systems, 1)
        if rows
        else 0
    )
    total_violations = sum(r["open_violations"] for r in rows)
    at_risk_count = sum(
        1
        for r in rows
        if r["open_violations"] > 0 or (r["days_since_revision"] or 0) > 30
    )

    env = Environment(loader=BaseLoader())
    template = env.from_string(_PORTFOLIO_PDF_TEMPLATE)
    html_content = template.render(
        org_name=org.name,
        gen_date=date.today().isoformat(),
        total_systems=total_systems,
        avg_completeness=avg_completeness,
        total_violations=total_violations,
        at_risk_count=at_risk_count,
        rows=rows,
    )
    return HTML(string=html_content).write_pdf()
